package com.sm.mybatis.mb;

import com.sm.mybatis.mb.CreditsDiscount;
import com.sm.mybatis.mb.CreditsDiscountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CreditsDiscountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_credits_discount
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	int countByExample(CreditsDiscountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_credits_discount
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	int deleteByExample(CreditsDiscountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_credits_discount
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	int deleteByPrimaryKey(String vipLevel);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_credits_discount
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	int insert(CreditsDiscount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_credits_discount
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	int insertSelective(CreditsDiscount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_credits_discount
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	List<CreditsDiscount> selectByExample(CreditsDiscountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_credits_discount
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	CreditsDiscount selectByPrimaryKey(String vipLevel);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_credits_discount
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	int updateByExampleSelective(@Param("record") CreditsDiscount record,
			@Param("example") CreditsDiscountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_credits_discount
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	int updateByExample(@Param("record") CreditsDiscount record,
			@Param("example") CreditsDiscountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_credits_discount
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	int updateByPrimaryKeySelective(CreditsDiscount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_credits_discount
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	int updateByPrimaryKey(CreditsDiscount record);
}