package com.sm.mybatis.mb;

public class CreditsDiscount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_credits_discount.Vip_Level
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private String vipLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_credits_discount.Credits_Start_Integral
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private Integer creditsStartIntegral;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_credits_discount.Credits_End_Integral
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private Integer creditsEndIntegral;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_credits_discount.Discount
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private String discount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_credits_discount.Vip_Level
	 * @return  the value of t_credits_discount.Vip_Level
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public String getVipLevel() {
		return vipLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_credits_discount.Vip_Level
	 * @param vipLevel  the value for t_credits_discount.Vip_Level
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setVipLevel(String vipLevel) {
		this.vipLevel = vipLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_credits_discount.Credits_Start_Integral
	 * @return  the value of t_credits_discount.Credits_Start_Integral
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public Integer getCreditsStartIntegral() {
		return creditsStartIntegral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_credits_discount.Credits_Start_Integral
	 * @param creditsStartIntegral  the value for t_credits_discount.Credits_Start_Integral
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setCreditsStartIntegral(Integer creditsStartIntegral) {
		this.creditsStartIntegral = creditsStartIntegral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_credits_discount.Credits_End_Integral
	 * @return  the value of t_credits_discount.Credits_End_Integral
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public Integer getCreditsEndIntegral() {
		return creditsEndIntegral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_credits_discount.Credits_End_Integral
	 * @param creditsEndIntegral  the value for t_credits_discount.Credits_End_Integral
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setCreditsEndIntegral(Integer creditsEndIntegral) {
		this.creditsEndIntegral = creditsEndIntegral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_credits_discount.Discount
	 * @return  the value of t_credits_discount.Discount
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public String getDiscount() {
		return discount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_credits_discount.Discount
	 * @param discount  the value for t_credits_discount.Discount
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setDiscount(String discount) {
		this.discount = discount;
	}
}