package com.sm.mybatis.mb;


public class GoodsOrderKey {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.Goods_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.Order_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.Goods_ID
     *
     * @return the value of t_goods_order.Goods_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.Goods_ID
     *
     * @param goodsId the value for t_goods_order.Goods_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.Order_ID
     *
     * @return the value of t_goods_order.Order_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.Order_ID
     *
     * @param orderId the value for t_goods_order.Order_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}