package com.sm.mybatis.mb;

import com.sm.mybatis.mb.GoodsOrderExample;
import com.sm.mybatis.mb.GoodsOrderKey;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface GoodsOrderMapper {
	
	List<GoodsOrderKey> selectOnceByMap(Map<String, Object> map);
	
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int countByExample(GoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int deleteByExample(GoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int deleteByPrimaryKey(GoodsOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int insert(GoodsOrderKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int insertSelective(GoodsOrderKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    List<GoodsOrderKey> selectByExample(GoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int updateByExampleSelective(@Param("record") GoodsOrderKey record, @Param("example") GoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int updateByExample(@Param("record") GoodsOrderKey record, @Param("example") GoodsOrderExample example);
}