package com.sm.mybatis.mb;

import com.sm.mybatis.mb.GoodsStock;
import com.sm.mybatis.mb.GoodsStockExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface GoodsStockMapper {
	
	

	//自定义
		List<GoodsStock> selectOnceByMap(Map <String, Object> map);
		//查找全部
	    List<GoodsStock> selectAll();
	//汪杰
	    List<GoodsStock> selectGoodsStockByMap(Map <String, Object> map);
	   int selectCountByGoodsStock(Map <String, Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int countByExample(GoodsStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int deleteByExample(GoodsStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int deleteByPrimaryKey(Integer goodsStockId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int insert(GoodsStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int insertSelective(GoodsStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    List<GoodsStock> selectByExample(GoodsStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    GoodsStock selectByPrimaryKey(Integer goodsStockId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int updateByExampleSelective(@Param("record") GoodsStock record, @Param("example") GoodsStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int updateByExample(@Param("record") GoodsStock record, @Param("example") GoodsStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int updateByPrimaryKeySelective(GoodsStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int updateByPrimaryKey(GoodsStock record);
}