package com.sm.mybatis.mb;

public class Goods {
	
	
	private GoodsStock goodsstock;
	
	
	
    public GoodsStock getGoodsstock() {
		return goodsstock;
	}

	public void setGoodsstock(GoodsStock goodsstock) {
		this.goodsstock = goodsstock;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.Goods_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.Goods_Name
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.Goods_Price
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private Float goodsPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.Goods_ID
     *
     * @return the value of t_goods.Goods_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.Goods_ID
     *
     * @param goodsId the value for t_goods.Goods_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.Goods_Name
     *
     * @return the value of t_goods.Goods_Name
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.Goods_Name
     *
     * @param goodsName the value for t_goods.Goods_Name
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.Goods_Price
     *
     * @return the value of t_goods.Goods_Price
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public Float getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.Goods_Price
     *
     * @param goodsPrice the value for t_goods.Goods_Price
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setGoodsPrice(Float goodsPrice) {
        this.goodsPrice = goodsPrice;
    }
}