package com.sm.mybatis.mb;

import java.util.Date;

public class InStock {
	
	private Goods goods;//添加一个对象
	private Stock stock;//添加一个对象
	
	
    public Goods getGoods() {
		return goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	public Stock getStock() {
		return stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_in_stock.In_Stock_ID
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    private Integer inStockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_in_stock.In_Stock_Time
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    private Date inStockTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_in_stock.Stock_ID
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    private Integer stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_in_stock.In_Stock_Principal
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    private Integer inStockPrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_in_stock.Goods_ID
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_in_stock.Goods_In_Num
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    private Integer goodsInNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_in_stock.In_Stock_ID
     *
     * @return the value of t_in_stock.In_Stock_ID
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public Integer getInStockId() {
        return inStockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_in_stock.In_Stock_ID
     *
     * @param inStockId the value for t_in_stock.In_Stock_ID
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public void setInStockId(Integer inStockId) {
        this.inStockId = inStockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_in_stock.In_Stock_Time
     *
     * @return the value of t_in_stock.In_Stock_Time
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public Date getInStockTime() {
        return inStockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_in_stock.In_Stock_Time
     *
     * @param inStockTime the value for t_in_stock.In_Stock_Time
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public void setInStockTime(Date inStockTime) {
        this.inStockTime = inStockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_in_stock.Stock_ID
     *
     * @return the value of t_in_stock.Stock_ID
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_in_stock.Stock_ID
     *
     * @param stockId the value for t_in_stock.Stock_ID
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_in_stock.In_Stock_Principal
     *
     * @return the value of t_in_stock.In_Stock_Principal
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public Integer getInStockPrincipal() {
        return inStockPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_in_stock.In_Stock_Principal
     *
     * @param inStockPrincipal the value for t_in_stock.In_Stock_Principal
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public void setInStockPrincipal(Integer inStockPrincipal) {
        this.inStockPrincipal = inStockPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_in_stock.Goods_ID
     *
     * @return the value of t_in_stock.Goods_ID
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_in_stock.Goods_ID
     *
     * @param goodsId the value for t_in_stock.Goods_ID
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_in_stock.Goods_In_Num
     *
     * @return the value of t_in_stock.Goods_In_Num
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public Integer getGoodsInNum() {
        return goodsInNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_in_stock.Goods_In_Num
     *
     * @param goodsInNum the value for t_in_stock.Goods_In_Num
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public void setGoodsInNum(Integer goodsInNum) {
        this.goodsInNum = goodsInNum;
    }
}