package com.sm.mybatis.mb;

import com.sm.mybatis.mb.InStock;
import com.sm.mybatis.mb.InStockExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface InStockMapper {
	
	//自定义方法...()添加一个方法
			List<InStock> selectOnceByMap(Map <String, Object> map);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_in_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int countByExample(InStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_in_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int deleteByExample(InStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_in_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int deleteByPrimaryKey(Integer inStockId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_in_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int insert(InStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_in_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int insertSelective(InStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_in_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    List<InStock> selectByExample(InStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_in_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    InStock selectByPrimaryKey(Integer inStockId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_in_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int updateByExampleSelective(@Param("record") InStock record, @Param("example") InStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_in_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int updateByExample(@Param("record") InStock record, @Param("example") InStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_in_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int updateByPrimaryKeySelective(InStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_in_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int updateByPrimaryKey(InStock record);
}