package com.sm.mybatis.mb;

public class LimitPower {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_limit_power.L_P_ID
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private Integer lPId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_limit_power.L_P_Name
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private String lPName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_limit_power.L_P_Description
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private String lPDescription;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_limit_power.L_P_ID
	 * @return  the value of t_limit_power.L_P_ID
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public Integer getlPId() {
		return lPId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_limit_power.L_P_ID
	 * @param lPId  the value for t_limit_power.L_P_ID
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setlPId(Integer lPId) {
		this.lPId = lPId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_limit_power.L_P_Name
	 * @return  the value of t_limit_power.L_P_Name
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public String getlPName() {
		return lPName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_limit_power.L_P_Name
	 * @param lPName  the value for t_limit_power.L_P_Name
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setlPName(String lPName) {
		this.lPName = lPName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_limit_power.L_P_Description
	 * @return  the value of t_limit_power.L_P_Description
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public String getlPDescription() {
		return lPDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_limit_power.L_P_Description
	 * @param lPDescription  the value for t_limit_power.L_P_Description
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setlPDescription(String lPDescription) {
		this.lPDescription = lPDescription;
	}
}