package com.sm.mybatis.mb;

public class LPRoleKey {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_lpower_role.LP_ID
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private Integer lpId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_lpower_role.Role_ID
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private Integer roleId;


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_lpower_role.LP_ID
	 * @return  the value of t_lpower_role.LP_ID
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public Integer getLpId() {
		return lpId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_lpower_role.LP_ID
	 * @param lpId  the value for t_lpower_role.LP_ID
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setLpId(Integer lpId) {
		this.lpId = lpId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_lpower_role.Role_ID
	 * @return  the value of t_lpower_role.Role_ID
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_lpower_role.Role_ID
	 * @param roleId  the value for t_lpower_role.Role_ID
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	private Role role;
	private LimitPower limitPower;
	
	
    public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public LimitPower getLimitPower() {
		return limitPower;
	}

	public void setLimitPower(LimitPower limitPower) {
		this.limitPower = limitPower;
	}
}