package com.sm.mybatis.mb;

import com.sm.mybatis.mb.Order;
import com.sm.mybatis.mb.OrderExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface OrderMapper {
	
	//自定义
  	List<Order> selectOnceByMap(Map <String, Object> map);
  	List<Order> selectWeiShenHe(Map <String, Object> map);
  	List<Order> selectAll();
  	List<Order> selectTwoByMap();
  	int selectCountByOrder(Map <String, Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    Order selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int updateByPrimaryKey(Order record);
}