package com.sm.mybatis.mb;

public class Order {
	
    private Supplier supplier;
    private State state;
    private Staff staff;
    private Goods goods;
	
    public Goods getGoods() {
		return goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	public Supplier getSupplier() {
		return supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	public State getState() {
		return state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public Staff getStaff() {
		return staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.Goods_Num
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private Integer goodsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.Goods_Order_Price
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private Float goodsOrderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.Supplier_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.Principal
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private Integer principal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.state_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private Integer stateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_ID
     *
     * @return the value of t_order.order_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_ID
     *
     * @param orderId the value for t_order.order_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.Goods_Num
     *
     * @return the value of t_order.Goods_Num
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public Integer getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.Goods_Num
     *
     * @param goodsNum the value for t_order.Goods_Num
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setGoodsNum(Integer goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.Goods_Order_Price
     *
     * @return the value of t_order.Goods_Order_Price
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public Float getGoodsOrderPrice() {
        return goodsOrderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.Goods_Order_Price
     *
     * @param goodsOrderPrice the value for t_order.Goods_Order_Price
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setGoodsOrderPrice(Float goodsOrderPrice) {
        this.goodsOrderPrice = goodsOrderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.Supplier_ID
     *
     * @return the value of t_order.Supplier_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.Supplier_ID
     *
     * @param supplierId the value for t_order.Supplier_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.Principal
     *
     * @return the value of t_order.Principal
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public Integer getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.Principal
     *
     * @param principal the value for t_order.Principal
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setPrincipal(Integer principal) {
        this.principal = principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.state_ID
     *
     * @return the value of t_order.state_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public Integer getStateId() {
        return stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.state_ID
     *
     * @param stateId the value for t_order.state_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }
}