package com.sm.mybatis.mb;

import java.util.Date;

public class OutStock {
	
	
	private Goods goods;//添加一个对象
	private Stock stock;//添加一个对象
	
    public Goods getGoods() {
		return goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	public Stock getStock() {
		return stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_stock.Out_Stock_ID
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    private Integer outStockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_stock.Out_Stock_Time
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    private Date outStockTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_stock.Stock_ID
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    private Integer stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_stock.Out_Stock_Principal
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    private Integer outStockPrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_stock.Goods_ID
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_stock.Goods_Out_Num
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    private Integer goodsOutNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_stock.Out_Stock_ID
     *
     * @return the value of t_out_stock.Out_Stock_ID
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public Integer getOutStockId() {
        return outStockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_stock.Out_Stock_ID
     *
     * @param outStockId the value for t_out_stock.Out_Stock_ID
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public void setOutStockId(Integer outStockId) {
        this.outStockId = outStockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_stock.Out_Stock_Time
     *
     * @return the value of t_out_stock.Out_Stock_Time
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public Date getOutStockTime() {
        return outStockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_stock.Out_Stock_Time
     *
     * @param outStockTime the value for t_out_stock.Out_Stock_Time
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public void setOutStockTime(Date outStockTime) {
        this.outStockTime = outStockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_stock.Stock_ID
     *
     * @return the value of t_out_stock.Stock_ID
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_stock.Stock_ID
     *
     * @param stockId the value for t_out_stock.Stock_ID
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_stock.Out_Stock_Principal
     *
     * @return the value of t_out_stock.Out_Stock_Principal
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public Integer getOutStockPrincipal() {
        return outStockPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_stock.Out_Stock_Principal
     *
     * @param outStockPrincipal the value for t_out_stock.Out_Stock_Principal
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public void setOutStockPrincipal(Integer outStockPrincipal) {
        this.outStockPrincipal = outStockPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_stock.Goods_ID
     *
     * @return the value of t_out_stock.Goods_ID
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_stock.Goods_ID
     *
     * @param goodsId the value for t_out_stock.Goods_ID
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_stock.Goods_Out_Num
     *
     * @return the value of t_out_stock.Goods_Out_Num
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public Integer getGoodsOutNum() {
        return goodsOutNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_stock.Goods_Out_Num
     *
     * @param goodsOutNum the value for t_out_stock.Goods_Out_Num
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    public void setGoodsOutNum(Integer goodsOutNum) {
        this.goodsOutNum = goodsOutNum;
    }
}