package com.sm.mybatis.mb;

import com.sm.mybatis.mb.OutStock;
import com.sm.mybatis.mb.OutStockExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface OutStockMapper {
	
	//自定义方法...()添加一个方法
			List<OutStock> selectOnceByMap(Map <String, Object> map);
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int countByExample(OutStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int deleteByExample(OutStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int deleteByPrimaryKey(Integer outStockId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int insert(OutStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int insertSelective(OutStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    List<OutStock> selectByExample(OutStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    OutStock selectByPrimaryKey(Integer outStockId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int updateByExampleSelective(@Param("record") OutStock record, @Param("example") OutStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int updateByExample(@Param("record") OutStock record, @Param("example") OutStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int updateByPrimaryKeySelective(OutStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_stock
     *
     * @mbggenerated Tue Jun 30 10:38:24 CST 2015
     */
    int updateByPrimaryKey(OutStock record);
}