package com.sm.mybatis.mb;

import com.sm.mybatis.mb.SaleBreakage;
import com.sm.mybatis.mb.SaleBreakageExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SaleBreakageMapper {
	
	
	 /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sale_breakage
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	int countByExample(SaleBreakageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sale_breakage
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	int deleteByExample(SaleBreakageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sale_breakage
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	int deleteByPrimaryKey(Integer breakageId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sale_breakage
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	int insert(SaleBreakage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sale_breakage
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	int insertSelective(SaleBreakage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sale_breakage
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	List<SaleBreakage> selectByExample(SaleBreakageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sale_breakage
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	SaleBreakage selectByPrimaryKey(Integer breakageId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sale_breakage
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	int updateByExampleSelective(@Param("record") SaleBreakage record,
			@Param("example") SaleBreakageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sale_breakage
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	int updateByExample(@Param("record") SaleBreakage record,
			@Param("example") SaleBreakageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sale_breakage
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	int updateByPrimaryKeySelective(SaleBreakage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sale_breakage
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	int updateByPrimaryKey(SaleBreakage record);
	int selectCountByBreak(Map <String, Object> map);
	List<SaleBreakage> selectOnceByMap();
	List<SaleBreakage> selectTwoByMap(Map <String, Object> map);
}