package com.sm.mybatis.mb;

import com.sm.mybatis.mb.SaleDetail;
import com.sm.mybatis.mb.SaleDetailExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SaleDetailMapper {
	

	//查找全部
    List<SaleDetail> selectAll();
	
	
	//自定义
	List<SaleDetail> selectOnceByMap(Map <String, Object> map);
		
	//自定义查询saleId为空的SaleDetail
	List<SaleDetail> selectSaleIdNull(Map <String, Object> map);
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sale_detail
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int countByExample(SaleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sale_detail
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int deleteByExample(SaleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sale_detail
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int deleteByPrimaryKey(Integer saleDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sale_detail
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int insert(SaleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sale_detail
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int insertSelective(SaleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sale_detail
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    List<SaleDetail> selectByExample(SaleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sale_detail
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    SaleDetail selectByPrimaryKey(Integer saleDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sale_detail
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int updateByExampleSelective(@Param("record") SaleDetail record, @Param("example") SaleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sale_detail
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int updateByExample(@Param("record") SaleDetail record, @Param("example") SaleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sale_detail
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int updateByPrimaryKeySelective(SaleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sale_detail
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int updateByPrimaryKey(SaleDetail record);
}