package com.sm.mybatis.mb;

public class SaleDetail {
	
	
	private Goods goods;
	private Sale sale;

	public Goods getGoods() {
		return goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	public Sale getSale() {
		return sale;
	}

	public void setSale(Sale sale) {
		this.sale = sale;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_detail.Sale_Detail_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private Integer saleDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_detail.Goods_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_detail.Number
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_detail.Price
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_detail.Goods_Discount
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private String goodsDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_detail.Sale_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private Integer saleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_detail.Sale_Detail_ID
     *
     * @return the value of t_sale_detail.Sale_Detail_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public Integer getSaleDetailId() {
        return saleDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_detail.Sale_Detail_ID
     *
     * @param saleDetailId the value for t_sale_detail.Sale_Detail_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setSaleDetailId(Integer saleDetailId) {
        this.saleDetailId = saleDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_detail.Goods_ID
     *
     * @return the value of t_sale_detail.Goods_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_detail.Goods_ID
     *
     * @param goodsId the value for t_sale_detail.Goods_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_detail.Number
     *
     * @return the value of t_sale_detail.Number
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_detail.Number
     *
     * @param number the value for t_sale_detail.Number
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_detail.Price
     *
     * @return the value of t_sale_detail.Price
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_detail.Price
     *
     * @param price the value for t_sale_detail.Price
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_detail.Goods_Discount
     *
     * @return the value of t_sale_detail.Goods_Discount
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public String getGoodsDiscount() {
        return goodsDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_detail.Goods_Discount
     *
     * @param goodsDiscount the value for t_sale_detail.Goods_Discount
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setGoodsDiscount(String goodsDiscount) {
        this.goodsDiscount = goodsDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_detail.Sale_ID
     *
     * @return the value of t_sale_detail.Sale_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public Integer getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_detail.Sale_ID
     *
     * @param saleId the value for t_sale_detail.Sale_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setSaleId(Integer saleId) {
        this.saleId = saleId;
    }
}