package com.sm.mybatis.mb;

import java.util.Date;

public class SaleBreakage {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sale_breakage.Breakage_ID
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	private Integer breakageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sale_breakage.Goods_ID
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	private Integer goodsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sale_breakage.Goods_Num
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	private Integer goodsNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sale_breakage.Stock_ID
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	private Integer stockId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sale_breakage.Staff_ID
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	private Integer staffId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sale_breakage.Breakage_time
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	private Date breakageTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sale_breakage.Breakage_remark
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	private String breakageRemark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sale_breakage.state_ID
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	private Integer stateId;



	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sale_breakage.Breakage_ID
	 * @return  the value of t_sale_breakage.Breakage_ID
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	public Integer getBreakageId() {
		return breakageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sale_breakage.Breakage_ID
	 * @param breakageId  the value for t_sale_breakage.Breakage_ID
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	public void setBreakageId(Integer breakageId) {
		this.breakageId = breakageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sale_breakage.Goods_ID
	 * @return  the value of t_sale_breakage.Goods_ID
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	public Integer getGoodsId() {
		return goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sale_breakage.Goods_ID
	 * @param goodsId  the value for t_sale_breakage.Goods_ID
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sale_breakage.Goods_Num
	 * @return  the value of t_sale_breakage.Goods_Num
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	public Integer getGoodsNum() {
		return goodsNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sale_breakage.Goods_Num
	 * @param goodsNum  the value for t_sale_breakage.Goods_Num
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	public void setGoodsNum(Integer goodsNum) {
		this.goodsNum = goodsNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sale_breakage.Stock_ID
	 * @return  the value of t_sale_breakage.Stock_ID
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	public Integer getStockId() {
		return stockId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sale_breakage.Stock_ID
	 * @param stockId  the value for t_sale_breakage.Stock_ID
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	public void setStockId(Integer stockId) {
		this.stockId = stockId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sale_breakage.Staff_ID
	 * @return  the value of t_sale_breakage.Staff_ID
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	public Integer getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sale_breakage.Staff_ID
	 * @param staffId  the value for t_sale_breakage.Staff_ID
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sale_breakage.Breakage_time
	 * @return  the value of t_sale_breakage.Breakage_time
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	public Date getBreakageTime() {
		return breakageTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sale_breakage.Breakage_time
	 * @param breakageTime  the value for t_sale_breakage.Breakage_time
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	public void setBreakageTime(Date breakageTime) {
		this.breakageTime = breakageTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sale_breakage.Breakage_remark
	 * @return  the value of t_sale_breakage.Breakage_remark
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	public String getBreakageRemark() {
		return breakageRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sale_breakage.Breakage_remark
	 * @param breakageRemark  the value for t_sale_breakage.Breakage_remark
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	public void setBreakageRemark(String breakageRemark) {
		this.breakageRemark = breakageRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sale_breakage.state_ID
	 * @return  the value of t_sale_breakage.state_ID
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	public Integer getStateId() {
		return stateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sale_breakage.state_ID
	 * @param stateId  the value for t_sale_breakage.state_ID
	 * @mbggenerated  Tue Jun 30 10:38:14 CST 2015
	 */
	public void setStateId(Integer stateId) {
		this.stateId = stateId;
	}

	private Staff staff;
	private State state;
	private Goods goods;
	private Stock stock;
	
	
	
    public Staff getStaff() {
		return staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public State getState() {
		return state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public Goods getGoods() {
		return goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	public Stock getStock() {
		return stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}
}