package com.sm.mybatis.mb;

import java.util.ArrayList;
import java.util.List;

public class StaffExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public StaffExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andStaffIdIsNull() {
			addCriterion("Staff_ID is null");
			return (Criteria) this;
		}

		public Criteria andStaffIdIsNotNull() {
			addCriterion("Staff_ID is not null");
			return (Criteria) this;
		}

		public Criteria andStaffIdEqualTo(Integer value) {
			addCriterion("Staff_ID =", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdNotEqualTo(Integer value) {
			addCriterion("Staff_ID <>", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdGreaterThan(Integer value) {
			addCriterion("Staff_ID >", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("Staff_ID >=", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdLessThan(Integer value) {
			addCriterion("Staff_ID <", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdLessThanOrEqualTo(Integer value) {
			addCriterion("Staff_ID <=", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdIn(List<Integer> values) {
			addCriterion("Staff_ID in", values, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdNotIn(List<Integer> values) {
			addCriterion("Staff_ID not in", values, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdBetween(Integer value1, Integer value2) {
			addCriterion("Staff_ID between", value1, value2, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdNotBetween(Integer value1, Integer value2) {
			addCriterion("Staff_ID not between", value1, value2, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffNameIsNull() {
			addCriterion("Staff_Name is null");
			return (Criteria) this;
		}

		public Criteria andStaffNameIsNotNull() {
			addCriterion("Staff_Name is not null");
			return (Criteria) this;
		}

		public Criteria andStaffNameEqualTo(String value) {
			addCriterion("Staff_Name =", value, "staffName");
			return (Criteria) this;
		}

		public Criteria andStaffNameNotEqualTo(String value) {
			addCriterion("Staff_Name <>", value, "staffName");
			return (Criteria) this;
		}

		public Criteria andStaffNameGreaterThan(String value) {
			addCriterion("Staff_Name >", value, "staffName");
			return (Criteria) this;
		}

		public Criteria andStaffNameGreaterThanOrEqualTo(String value) {
			addCriterion("Staff_Name >=", value, "staffName");
			return (Criteria) this;
		}

		public Criteria andStaffNameLessThan(String value) {
			addCriterion("Staff_Name <", value, "staffName");
			return (Criteria) this;
		}

		public Criteria andStaffNameLessThanOrEqualTo(String value) {
			addCriterion("Staff_Name <=", value, "staffName");
			return (Criteria) this;
		}

		public Criteria andStaffNameLike(String value) {
			addCriterion("Staff_Name like", value, "staffName");
			return (Criteria) this;
		}

		public Criteria andStaffNameNotLike(String value) {
			addCriterion("Staff_Name not like", value, "staffName");
			return (Criteria) this;
		}

		public Criteria andStaffNameIn(List<String> values) {
			addCriterion("Staff_Name in", values, "staffName");
			return (Criteria) this;
		}

		public Criteria andStaffNameNotIn(List<String> values) {
			addCriterion("Staff_Name not in", values, "staffName");
			return (Criteria) this;
		}

		public Criteria andStaffNameBetween(String value1, String value2) {
			addCriterion("Staff_Name between", value1, value2, "staffName");
			return (Criteria) this;
		}

		public Criteria andStaffNameNotBetween(String value1, String value2) {
			addCriterion("Staff_Name not between", value1, value2, "staffName");
			return (Criteria) this;
		}

		public Criteria andStaffIdentityCardIsNull() {
			addCriterion("Staff_Identity_Card is null");
			return (Criteria) this;
		}

		public Criteria andStaffIdentityCardIsNotNull() {
			addCriterion("Staff_Identity_Card is not null");
			return (Criteria) this;
		}

		public Criteria andStaffIdentityCardEqualTo(String value) {
			addCriterion("Staff_Identity_Card =", value, "staffIdentityCard");
			return (Criteria) this;
		}

		public Criteria andStaffIdentityCardNotEqualTo(String value) {
			addCriterion("Staff_Identity_Card <>", value, "staffIdentityCard");
			return (Criteria) this;
		}

		public Criteria andStaffIdentityCardGreaterThan(String value) {
			addCriterion("Staff_Identity_Card >", value, "staffIdentityCard");
			return (Criteria) this;
		}

		public Criteria andStaffIdentityCardGreaterThanOrEqualTo(String value) {
			addCriterion("Staff_Identity_Card >=", value, "staffIdentityCard");
			return (Criteria) this;
		}

		public Criteria andStaffIdentityCardLessThan(String value) {
			addCriterion("Staff_Identity_Card <", value, "staffIdentityCard");
			return (Criteria) this;
		}

		public Criteria andStaffIdentityCardLessThanOrEqualTo(String value) {
			addCriterion("Staff_Identity_Card <=", value, "staffIdentityCard");
			return (Criteria) this;
		}

		public Criteria andStaffIdentityCardLike(String value) {
			addCriterion("Staff_Identity_Card like", value, "staffIdentityCard");
			return (Criteria) this;
		}

		public Criteria andStaffIdentityCardNotLike(String value) {
			addCriterion("Staff_Identity_Card not like", value,
					"staffIdentityCard");
			return (Criteria) this;
		}

		public Criteria andStaffIdentityCardIn(List<String> values) {
			addCriterion("Staff_Identity_Card in", values, "staffIdentityCard");
			return (Criteria) this;
		}

		public Criteria andStaffIdentityCardNotIn(List<String> values) {
			addCriterion("Staff_Identity_Card not in", values,
					"staffIdentityCard");
			return (Criteria) this;
		}

		public Criteria andStaffIdentityCardBetween(String value1, String value2) {
			addCriterion("Staff_Identity_Card between", value1, value2,
					"staffIdentityCard");
			return (Criteria) this;
		}

		public Criteria andStaffIdentityCardNotBetween(String value1,
				String value2) {
			addCriterion("Staff_Identity_Card not between", value1, value2,
					"staffIdentityCard");
			return (Criteria) this;
		}

		public Criteria andSexIsNull() {
			addCriterion("Sex is null");
			return (Criteria) this;
		}

		public Criteria andSexIsNotNull() {
			addCriterion("Sex is not null");
			return (Criteria) this;
		}

		public Criteria andSexEqualTo(String value) {
			addCriterion("Sex =", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotEqualTo(String value) {
			addCriterion("Sex <>", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThan(String value) {
			addCriterion("Sex >", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThanOrEqualTo(String value) {
			addCriterion("Sex >=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThan(String value) {
			addCriterion("Sex <", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThanOrEqualTo(String value) {
			addCriterion("Sex <=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLike(String value) {
			addCriterion("Sex like", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotLike(String value) {
			addCriterion("Sex not like", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexIn(List<String> values) {
			addCriterion("Sex in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotIn(List<String> values) {
			addCriterion("Sex not in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexBetween(String value1, String value2) {
			addCriterion("Sex between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotBetween(String value1, String value2) {
			addCriterion("Sex not between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andAgeIsNull() {
			addCriterion("Age is null");
			return (Criteria) this;
		}

		public Criteria andAgeIsNotNull() {
			addCriterion("Age is not null");
			return (Criteria) this;
		}

		public Criteria andAgeEqualTo(Integer value) {
			addCriterion("Age =", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotEqualTo(Integer value) {
			addCriterion("Age <>", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeGreaterThan(Integer value) {
			addCriterion("Age >", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
			addCriterion("Age >=", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLessThan(Integer value) {
			addCriterion("Age <", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLessThanOrEqualTo(Integer value) {
			addCriterion("Age <=", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeIn(List<Integer> values) {
			addCriterion("Age in", values, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotIn(List<Integer> values) {
			addCriterion("Age not in", values, "age");
			return (Criteria) this;
		}

		public Criteria andAgeBetween(Integer value1, Integer value2) {
			addCriterion("Age between", value1, value2, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotBetween(Integer value1, Integer value2) {
			addCriterion("Age not between", value1, value2, "age");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberIsNull() {
			addCriterion("Phone_Number is null");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberIsNotNull() {
			addCriterion("Phone_Number is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberEqualTo(String value) {
			addCriterion("Phone_Number =", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotEqualTo(String value) {
			addCriterion("Phone_Number <>", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberGreaterThan(String value) {
			addCriterion("Phone_Number >", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberGreaterThanOrEqualTo(String value) {
			addCriterion("Phone_Number >=", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberLessThan(String value) {
			addCriterion("Phone_Number <", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberLessThanOrEqualTo(String value) {
			addCriterion("Phone_Number <=", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberLike(String value) {
			addCriterion("Phone_Number like", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotLike(String value) {
			addCriterion("Phone_Number not like", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberIn(List<String> values) {
			addCriterion("Phone_Number in", values, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotIn(List<String> values) {
			addCriterion("Phone_Number not in", values, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberBetween(String value1, String value2) {
			addCriterion("Phone_Number between", value1, value2, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotBetween(String value1, String value2) {
			addCriterion("Phone_Number not between", value1, value2,
					"phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("Password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("Password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("Password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("Password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("Password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("Password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("Password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("Password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("Password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("Password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("Password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("Password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("Password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("Password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andRoleIdIsNull() {
			addCriterion("Role_Id is null");
			return (Criteria) this;
		}

		public Criteria andRoleIdIsNotNull() {
			addCriterion("Role_Id is not null");
			return (Criteria) this;
		}

		public Criteria andRoleIdEqualTo(Integer value) {
			addCriterion("Role_Id =", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotEqualTo(Integer value) {
			addCriterion("Role_Id <>", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdGreaterThan(Integer value) {
			addCriterion("Role_Id >", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("Role_Id >=", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdLessThan(Integer value) {
			addCriterion("Role_Id <", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdLessThanOrEqualTo(Integer value) {
			addCriterion("Role_Id <=", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdIn(List<Integer> values) {
			addCriterion("Role_Id in", values, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotIn(List<Integer> values) {
			addCriterion("Role_Id not in", values, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdBetween(Integer value1, Integer value2) {
			addCriterion("Role_Id between", value1, value2, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotBetween(Integer value1, Integer value2) {
			addCriterion("Role_Id not between", value1, value2, "roleId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_staff
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 15 14:25:48 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}