package com.sm.mybatis.mb;



public class Staff {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_staff.Staff_ID
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private Integer staffId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_staff.Staff_Name
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private String staffName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_staff.Staff_Identity_Card
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private String staffIdentityCard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_staff.Sex
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_staff.Age
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_staff.Phone_Number
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private String phoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_staff.Password
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_staff.Role_Id
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private Integer roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_staff.Staff_ID
	 * @return  the value of t_staff.Staff_ID
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public Integer getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_staff.Staff_ID
	 * @param staffId  the value for t_staff.Staff_ID
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_staff.Staff_Name
	 * @return  the value of t_staff.Staff_Name
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public String getStaffName() {
		return staffName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_staff.Staff_Name
	 * @param staffName  the value for t_staff.Staff_Name
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_staff.Staff_Identity_Card
	 * @return  the value of t_staff.Staff_Identity_Card
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public String getStaffIdentityCard() {
		return staffIdentityCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_staff.Staff_Identity_Card
	 * @param staffIdentityCard  the value for t_staff.Staff_Identity_Card
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setStaffIdentityCard(String staffIdentityCard) {
		this.staffIdentityCard = staffIdentityCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_staff.Sex
	 * @return  the value of t_staff.Sex
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_staff.Sex
	 * @param sex  the value for t_staff.Sex
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_staff.Age
	 * @return  the value of t_staff.Age
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_staff.Age
	 * @param age  the value for t_staff.Age
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_staff.Phone_Number
	 * @return  the value of t_staff.Phone_Number
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_staff.Phone_Number
	 * @param phoneNumber  the value for t_staff.Phone_Number
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_staff.Password
	 * @return  the value of t_staff.Password
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_staff.Password
	 * @param password  the value for t_staff.Password
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_staff.Role_Id
	 * @return  the value of t_staff.Role_Id
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_staff.Role_Id
	 * @param roleId  the value for t_staff.Role_Id
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	private Role role;

    public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

}