package com.sm.mybatis.mb;

import com.sm.mybatis.mb.Staff;
import com.sm.mybatis.mb.StaffExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;


public interface StaffMapper {
	
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	int countByExample(StaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	int deleteByExample(StaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	int deleteByPrimaryKey(Integer staffId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	int insert(Staff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	int insertSelective(Staff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	List<Staff> selectByExample(StaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	Staff selectByPrimaryKey(Integer staffId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Staff record,
			@Param("example") StaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	int updateByExample(@Param("record") Staff record,
			@Param("example") StaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	int updateByPrimaryKeySelective(Staff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_staff
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	int updateByPrimaryKey(Staff record);

		//自定义方法
		List<Staff> selectOnceByMap(Map <String, Object> map);
		int selectCountByStaff(Map <String, Object> map);
		List<Staff> selectAll();
		
//		段浩
		/*List<TStaff> selectOnceByMap(Map <String, Object> map);*/
		/* List<Staff> selectAll();*/
}