package com.sm.mybatis.mb;

public class State {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_state.state_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private Integer stateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_state.state_Name
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    private String stateName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_state.state_ID
     *
     * @return the value of t_state.state_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public Integer getStateId() {
        return stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_state.state_ID
     *
     * @param stateId the value for t_state.state_ID
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_state.state_Name
     *
     * @return the value of t_state.state_Name
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public String getStateName() {
        return stateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_state.state_Name
     *
     * @param stateName the value for t_state.state_Name
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }
}