package com.sm.mybatis.mb;

import com.sm.mybatis.mb.State;
import com.sm.mybatis.mb.StateExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface StateMapper {
	

	    //自定义
		List<State> selectOnceByMap(Map<String, Object> params);
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_state
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int countByExample(StateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_state
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int deleteByExample(StateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_state
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int deleteByPrimaryKey(Integer stateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_state
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int insert(State record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_state
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int insertSelective(State record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_state
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    List<State> selectByExample(StateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_state
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    State selectByPrimaryKey(Integer stateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_state
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int updateByExampleSelective(@Param("record") State record, @Param("example") StateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_state
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int updateByExample(@Param("record") State record, @Param("example") StateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_state
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int updateByPrimaryKeySelective(State record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_state
     *
     * @mbggenerated Fri Jun 26 15:15:34 CST 2015
     */
    int updateByPrimaryKey(State record);
}