package com.sm.mybatis.mb;

public class Supplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.Supplier_ID
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.Supplier_Name
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.Supplier_Address
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    private String supplierAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.Supplier_Phone
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    private String supplierPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.Supplier_ID
     *
     * @return the value of t_supplier.Supplier_ID
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.Supplier_ID
     *
     * @param supplierId the value for t_supplier.Supplier_ID
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.Supplier_Name
     *
     * @return the value of t_supplier.Supplier_Name
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.Supplier_Name
     *
     * @param supplierName the value for t_supplier.Supplier_Name
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.Supplier_Address
     *
     * @return the value of t_supplier.Supplier_Address
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    public String getSupplierAddress() {
        return supplierAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.Supplier_Address
     *
     * @param supplierAddress the value for t_supplier.Supplier_Address
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    public void setSupplierAddress(String supplierAddress) {
        this.supplierAddress = supplierAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.Supplier_Phone
     *
     * @return the value of t_supplier.Supplier_Phone
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    public String getSupplierPhone() {
        return supplierPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.Supplier_Phone
     *
     * @param supplierPhone the value for t_supplier.Supplier_Phone
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    public void setSupplierPhone(String supplierPhone) {
        this.supplierPhone = supplierPhone;
    }
}