package com.sm.mybatis.mb;

import com.sm.mybatis.mb.Supplier;
import com.sm.mybatis.mb.SupplierExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SupplierMapper {
	
	int selectCountBySupplier(Map <String, Object> map);
	
	List<Supplier> selectAllBySupplier(Map <String, Object> map);
	
	
	//段浩
		List<Supplier> selectOnceByMap(Map <String, Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    int countByExample(SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    int deleteByExample(SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    int deleteByPrimaryKey(Integer supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    int insert(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    int insertSelective(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    List<Supplier> selectByExample(SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    Supplier selectByPrimaryKey(Integer supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    int updateByExampleSelective(@Param("record") Supplier record, @Param("example") SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    int updateByExample(@Param("record") Supplier record, @Param("example") SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    int updateByPrimaryKeySelective(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbggenerated Thu Jun 25 10:51:08 CST 2015
     */
    int updateByPrimaryKey(Supplier record);
}