package com.sm.mybatis.mb;

import java.util.Date;

public class Vip {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vip.Vip_ID
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private Integer vipId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vip.Vip_Password
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private String vipPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vip.Vip_Create_Time
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private Date vipCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vip.Vip_Vaild_Time
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private Date vipVaildTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vip.Vip_Con_Total
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private Float vipConTotal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vip.Vip_Level
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private String vipLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vip.Vip_Name
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private String vipName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vip.Vip_Identity_Card
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private String vipIdentityCard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vip.Vip_Address
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private String vipAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vip.Vip_Phone_Number
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	private String vipPhoneNumber;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vip.Vip_ID
	 * @return  the value of t_vip.Vip_ID
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public Integer getVipId() {
		return vipId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vip.Vip_ID
	 * @param vipId  the value for t_vip.Vip_ID
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setVipId(Integer vipId) {
		this.vipId = vipId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vip.Vip_Password
	 * @return  the value of t_vip.Vip_Password
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public String getVipPassword() {
		return vipPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vip.Vip_Password
	 * @param vipPassword  the value for t_vip.Vip_Password
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setVipPassword(String vipPassword) {
		this.vipPassword = vipPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vip.Vip_Create_Time
	 * @return  the value of t_vip.Vip_Create_Time
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public Date getVipCreateTime() {
		return vipCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vip.Vip_Create_Time
	 * @param vipCreateTime  the value for t_vip.Vip_Create_Time
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setVipCreateTime(Date vipCreateTime) {
		this.vipCreateTime = vipCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vip.Vip_Vaild_Time
	 * @return  the value of t_vip.Vip_Vaild_Time
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public Date getVipVaildTime() {
		return vipVaildTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vip.Vip_Vaild_Time
	 * @param vipVaildTime  the value for t_vip.Vip_Vaild_Time
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setVipVaildTime(Date vipVaildTime) {
		this.vipVaildTime = vipVaildTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vip.Vip_Con_Total
	 * @return  the value of t_vip.Vip_Con_Total
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public Float getVipConTotal() {
		return vipConTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vip.Vip_Con_Total
	 * @param vipConTotal  the value for t_vip.Vip_Con_Total
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setVipConTotal(Float vipConTotal) {
		this.vipConTotal = vipConTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vip.Vip_Level
	 * @return  the value of t_vip.Vip_Level
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public String getVipLevel() {
		return vipLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vip.Vip_Level
	 * @param vipLevel  the value for t_vip.Vip_Level
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setVipLevel(String vipLevel) {
		this.vipLevel = vipLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vip.Vip_Name
	 * @return  the value of t_vip.Vip_Name
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public String getVipName() {
		return vipName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vip.Vip_Name
	 * @param vipName  the value for t_vip.Vip_Name
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setVipName(String vipName) {
		this.vipName = vipName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vip.Vip_Identity_Card
	 * @return  the value of t_vip.Vip_Identity_Card
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public String getVipIdentityCard() {
		return vipIdentityCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vip.Vip_Identity_Card
	 * @param vipIdentityCard  the value for t_vip.Vip_Identity_Card
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setVipIdentityCard(String vipIdentityCard) {
		this.vipIdentityCard = vipIdentityCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vip.Vip_Address
	 * @return  the value of t_vip.Vip_Address
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public String getVipAddress() {
		return vipAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vip.Vip_Address
	 * @param vipAddress  the value for t_vip.Vip_Address
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setVipAddress(String vipAddress) {
		this.vipAddress = vipAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vip.Vip_Phone_Number
	 * @return  the value of t_vip.Vip_Phone_Number
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public String getVipPhoneNumber() {
		return vipPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vip.Vip_Phone_Number
	 * @param vipPhoneNumber  the value for t_vip.Vip_Phone_Number
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setVipPhoneNumber(String vipPhoneNumber) {
		this.vipPhoneNumber = vipPhoneNumber;
	}
}