package com.sm.mybatis.mb;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class VipExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_vip
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_vip
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_vip
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vip
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public VipExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vip
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vip
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vip
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vip
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vip
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vip
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vip
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vip
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vip
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vip
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_vip
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andVipIdIsNull() {
			addCriterion("Vip_ID is null");
			return (Criteria) this;
		}

		public Criteria andVipIdIsNotNull() {
			addCriterion("Vip_ID is not null");
			return (Criteria) this;
		}

		public Criteria andVipIdEqualTo(Integer value) {
			addCriterion("Vip_ID =", value, "vipId");
			return (Criteria) this;
		}

		public Criteria andVipIdNotEqualTo(Integer value) {
			addCriterion("Vip_ID <>", value, "vipId");
			return (Criteria) this;
		}

		public Criteria andVipIdGreaterThan(Integer value) {
			addCriterion("Vip_ID >", value, "vipId");
			return (Criteria) this;
		}

		public Criteria andVipIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("Vip_ID >=", value, "vipId");
			return (Criteria) this;
		}

		public Criteria andVipIdLessThan(Integer value) {
			addCriterion("Vip_ID <", value, "vipId");
			return (Criteria) this;
		}

		public Criteria andVipIdLessThanOrEqualTo(Integer value) {
			addCriterion("Vip_ID <=", value, "vipId");
			return (Criteria) this;
		}

		public Criteria andVipIdIn(List<Integer> values) {
			addCriterion("Vip_ID in", values, "vipId");
			return (Criteria) this;
		}

		public Criteria andVipIdNotIn(List<Integer> values) {
			addCriterion("Vip_ID not in", values, "vipId");
			return (Criteria) this;
		}

		public Criteria andVipIdBetween(Integer value1, Integer value2) {
			addCriterion("Vip_ID between", value1, value2, "vipId");
			return (Criteria) this;
		}

		public Criteria andVipIdNotBetween(Integer value1, Integer value2) {
			addCriterion("Vip_ID not between", value1, value2, "vipId");
			return (Criteria) this;
		}

		public Criteria andVipPasswordIsNull() {
			addCriterion("Vip_Password is null");
			return (Criteria) this;
		}

		public Criteria andVipPasswordIsNotNull() {
			addCriterion("Vip_Password is not null");
			return (Criteria) this;
		}

		public Criteria andVipPasswordEqualTo(String value) {
			addCriterion("Vip_Password =", value, "vipPassword");
			return (Criteria) this;
		}

		public Criteria andVipPasswordNotEqualTo(String value) {
			addCriterion("Vip_Password <>", value, "vipPassword");
			return (Criteria) this;
		}

		public Criteria andVipPasswordGreaterThan(String value) {
			addCriterion("Vip_Password >", value, "vipPassword");
			return (Criteria) this;
		}

		public Criteria andVipPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("Vip_Password >=", value, "vipPassword");
			return (Criteria) this;
		}

		public Criteria andVipPasswordLessThan(String value) {
			addCriterion("Vip_Password <", value, "vipPassword");
			return (Criteria) this;
		}

		public Criteria andVipPasswordLessThanOrEqualTo(String value) {
			addCriterion("Vip_Password <=", value, "vipPassword");
			return (Criteria) this;
		}

		public Criteria andVipPasswordLike(String value) {
			addCriterion("Vip_Password like", value, "vipPassword");
			return (Criteria) this;
		}

		public Criteria andVipPasswordNotLike(String value) {
			addCriterion("Vip_Password not like", value, "vipPassword");
			return (Criteria) this;
		}

		public Criteria andVipPasswordIn(List<String> values) {
			addCriterion("Vip_Password in", values, "vipPassword");
			return (Criteria) this;
		}

		public Criteria andVipPasswordNotIn(List<String> values) {
			addCriterion("Vip_Password not in", values, "vipPassword");
			return (Criteria) this;
		}

		public Criteria andVipPasswordBetween(String value1, String value2) {
			addCriterion("Vip_Password between", value1, value2, "vipPassword");
			return (Criteria) this;
		}

		public Criteria andVipPasswordNotBetween(String value1, String value2) {
			addCriterion("Vip_Password not between", value1, value2,
					"vipPassword");
			return (Criteria) this;
		}

		public Criteria andVipCreateTimeIsNull() {
			addCriterion("Vip_Create_Time is null");
			return (Criteria) this;
		}

		public Criteria andVipCreateTimeIsNotNull() {
			addCriterion("Vip_Create_Time is not null");
			return (Criteria) this;
		}

		public Criteria andVipCreateTimeEqualTo(Date value) {
			addCriterionForJDBCDate("Vip_Create_Time =", value, "vipCreateTime");
			return (Criteria) this;
		}

		public Criteria andVipCreateTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("Vip_Create_Time <>", value,
					"vipCreateTime");
			return (Criteria) this;
		}

		public Criteria andVipCreateTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("Vip_Create_Time >", value, "vipCreateTime");
			return (Criteria) this;
		}

		public Criteria andVipCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("Vip_Create_Time >=", value,
					"vipCreateTime");
			return (Criteria) this;
		}

		public Criteria andVipCreateTimeLessThan(Date value) {
			addCriterionForJDBCDate("Vip_Create_Time <", value, "vipCreateTime");
			return (Criteria) this;
		}

		public Criteria andVipCreateTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("Vip_Create_Time <=", value,
					"vipCreateTime");
			return (Criteria) this;
		}

		public Criteria andVipCreateTimeIn(List<Date> values) {
			addCriterionForJDBCDate("Vip_Create_Time in", values,
					"vipCreateTime");
			return (Criteria) this;
		}

		public Criteria andVipCreateTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("Vip_Create_Time not in", values,
					"vipCreateTime");
			return (Criteria) this;
		}

		public Criteria andVipCreateTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("Vip_Create_Time between", value1, value2,
					"vipCreateTime");
			return (Criteria) this;
		}

		public Criteria andVipCreateTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("Vip_Create_Time not between", value1,
					value2, "vipCreateTime");
			return (Criteria) this;
		}

		public Criteria andVipVaildTimeIsNull() {
			addCriterion("Vip_Vaild_Time is null");
			return (Criteria) this;
		}

		public Criteria andVipVaildTimeIsNotNull() {
			addCriterion("Vip_Vaild_Time is not null");
			return (Criteria) this;
		}

		public Criteria andVipVaildTimeEqualTo(Date value) {
			addCriterionForJDBCDate("Vip_Vaild_Time =", value, "vipVaildTime");
			return (Criteria) this;
		}

		public Criteria andVipVaildTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("Vip_Vaild_Time <>", value, "vipVaildTime");
			return (Criteria) this;
		}

		public Criteria andVipVaildTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("Vip_Vaild_Time >", value, "vipVaildTime");
			return (Criteria) this;
		}

		public Criteria andVipVaildTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("Vip_Vaild_Time >=", value, "vipVaildTime");
			return (Criteria) this;
		}

		public Criteria andVipVaildTimeLessThan(Date value) {
			addCriterionForJDBCDate("Vip_Vaild_Time <", value, "vipVaildTime");
			return (Criteria) this;
		}

		public Criteria andVipVaildTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("Vip_Vaild_Time <=", value, "vipVaildTime");
			return (Criteria) this;
		}

		public Criteria andVipVaildTimeIn(List<Date> values) {
			addCriterionForJDBCDate("Vip_Vaild_Time in", values, "vipVaildTime");
			return (Criteria) this;
		}

		public Criteria andVipVaildTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("Vip_Vaild_Time not in", values,
					"vipVaildTime");
			return (Criteria) this;
		}

		public Criteria andVipVaildTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("Vip_Vaild_Time between", value1, value2,
					"vipVaildTime");
			return (Criteria) this;
		}

		public Criteria andVipVaildTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("Vip_Vaild_Time not between", value1,
					value2, "vipVaildTime");
			return (Criteria) this;
		}

		public Criteria andVipConTotalIsNull() {
			addCriterion("Vip_Con_Total is null");
			return (Criteria) this;
		}

		public Criteria andVipConTotalIsNotNull() {
			addCriterion("Vip_Con_Total is not null");
			return (Criteria) this;
		}

		public Criteria andVipConTotalEqualTo(Float value) {
			addCriterion("Vip_Con_Total =", value, "vipConTotal");
			return (Criteria) this;
		}

		public Criteria andVipConTotalNotEqualTo(Float value) {
			addCriterion("Vip_Con_Total <>", value, "vipConTotal");
			return (Criteria) this;
		}

		public Criteria andVipConTotalGreaterThan(Float value) {
			addCriterion("Vip_Con_Total >", value, "vipConTotal");
			return (Criteria) this;
		}

		public Criteria andVipConTotalGreaterThanOrEqualTo(Float value) {
			addCriterion("Vip_Con_Total >=", value, "vipConTotal");
			return (Criteria) this;
		}

		public Criteria andVipConTotalLessThan(Float value) {
			addCriterion("Vip_Con_Total <", value, "vipConTotal");
			return (Criteria) this;
		}

		public Criteria andVipConTotalLessThanOrEqualTo(Float value) {
			addCriterion("Vip_Con_Total <=", value, "vipConTotal");
			return (Criteria) this;
		}

		public Criteria andVipConTotalIn(List<Float> values) {
			addCriterion("Vip_Con_Total in", values, "vipConTotal");
			return (Criteria) this;
		}

		public Criteria andVipConTotalNotIn(List<Float> values) {
			addCriterion("Vip_Con_Total not in", values, "vipConTotal");
			return (Criteria) this;
		}

		public Criteria andVipConTotalBetween(Float value1, Float value2) {
			addCriterion("Vip_Con_Total between", value1, value2, "vipConTotal");
			return (Criteria) this;
		}

		public Criteria andVipConTotalNotBetween(Float value1, Float value2) {
			addCriterion("Vip_Con_Total not between", value1, value2,
					"vipConTotal");
			return (Criteria) this;
		}

		public Criteria andVipLevelIsNull() {
			addCriterion("Vip_Level is null");
			return (Criteria) this;
		}

		public Criteria andVipLevelIsNotNull() {
			addCriterion("Vip_Level is not null");
			return (Criteria) this;
		}

		public Criteria andVipLevelEqualTo(String value) {
			addCriterion("Vip_Level =", value, "vipLevel");
			return (Criteria) this;
		}

		public Criteria andVipLevelNotEqualTo(String value) {
			addCriterion("Vip_Level <>", value, "vipLevel");
			return (Criteria) this;
		}

		public Criteria andVipLevelGreaterThan(String value) {
			addCriterion("Vip_Level >", value, "vipLevel");
			return (Criteria) this;
		}

		public Criteria andVipLevelGreaterThanOrEqualTo(String value) {
			addCriterion("Vip_Level >=", value, "vipLevel");
			return (Criteria) this;
		}

		public Criteria andVipLevelLessThan(String value) {
			addCriterion("Vip_Level <", value, "vipLevel");
			return (Criteria) this;
		}

		public Criteria andVipLevelLessThanOrEqualTo(String value) {
			addCriterion("Vip_Level <=", value, "vipLevel");
			return (Criteria) this;
		}

		public Criteria andVipLevelLike(String value) {
			addCriterion("Vip_Level like", value, "vipLevel");
			return (Criteria) this;
		}

		public Criteria andVipLevelNotLike(String value) {
			addCriterion("Vip_Level not like", value, "vipLevel");
			return (Criteria) this;
		}

		public Criteria andVipLevelIn(List<String> values) {
			addCriterion("Vip_Level in", values, "vipLevel");
			return (Criteria) this;
		}

		public Criteria andVipLevelNotIn(List<String> values) {
			addCriterion("Vip_Level not in", values, "vipLevel");
			return (Criteria) this;
		}

		public Criteria andVipLevelBetween(String value1, String value2) {
			addCriterion("Vip_Level between", value1, value2, "vipLevel");
			return (Criteria) this;
		}

		public Criteria andVipLevelNotBetween(String value1, String value2) {
			addCriterion("Vip_Level not between", value1, value2, "vipLevel");
			return (Criteria) this;
		}

		public Criteria andVipNameIsNull() {
			addCriterion("Vip_Name is null");
			return (Criteria) this;
		}

		public Criteria andVipNameIsNotNull() {
			addCriterion("Vip_Name is not null");
			return (Criteria) this;
		}

		public Criteria andVipNameEqualTo(String value) {
			addCriterion("Vip_Name =", value, "vipName");
			return (Criteria) this;
		}

		public Criteria andVipNameNotEqualTo(String value) {
			addCriterion("Vip_Name <>", value, "vipName");
			return (Criteria) this;
		}

		public Criteria andVipNameGreaterThan(String value) {
			addCriterion("Vip_Name >", value, "vipName");
			return (Criteria) this;
		}

		public Criteria andVipNameGreaterThanOrEqualTo(String value) {
			addCriterion("Vip_Name >=", value, "vipName");
			return (Criteria) this;
		}

		public Criteria andVipNameLessThan(String value) {
			addCriterion("Vip_Name <", value, "vipName");
			return (Criteria) this;
		}

		public Criteria andVipNameLessThanOrEqualTo(String value) {
			addCriterion("Vip_Name <=", value, "vipName");
			return (Criteria) this;
		}

		public Criteria andVipNameLike(String value) {
			addCriterion("Vip_Name like", value, "vipName");
			return (Criteria) this;
		}

		public Criteria andVipNameNotLike(String value) {
			addCriterion("Vip_Name not like", value, "vipName");
			return (Criteria) this;
		}

		public Criteria andVipNameIn(List<String> values) {
			addCriterion("Vip_Name in", values, "vipName");
			return (Criteria) this;
		}

		public Criteria andVipNameNotIn(List<String> values) {
			addCriterion("Vip_Name not in", values, "vipName");
			return (Criteria) this;
		}

		public Criteria andVipNameBetween(String value1, String value2) {
			addCriterion("Vip_Name between", value1, value2, "vipName");
			return (Criteria) this;
		}

		public Criteria andVipNameNotBetween(String value1, String value2) {
			addCriterion("Vip_Name not between", value1, value2, "vipName");
			return (Criteria) this;
		}

		public Criteria andVipIdentityCardIsNull() {
			addCriterion("Vip_Identity_Card is null");
			return (Criteria) this;
		}

		public Criteria andVipIdentityCardIsNotNull() {
			addCriterion("Vip_Identity_Card is not null");
			return (Criteria) this;
		}

		public Criteria andVipIdentityCardEqualTo(String value) {
			addCriterion("Vip_Identity_Card =", value, "vipIdentityCard");
			return (Criteria) this;
		}

		public Criteria andVipIdentityCardNotEqualTo(String value) {
			addCriterion("Vip_Identity_Card <>", value, "vipIdentityCard");
			return (Criteria) this;
		}

		public Criteria andVipIdentityCardGreaterThan(String value) {
			addCriterion("Vip_Identity_Card >", value, "vipIdentityCard");
			return (Criteria) this;
		}

		public Criteria andVipIdentityCardGreaterThanOrEqualTo(String value) {
			addCriterion("Vip_Identity_Card >=", value, "vipIdentityCard");
			return (Criteria) this;
		}

		public Criteria andVipIdentityCardLessThan(String value) {
			addCriterion("Vip_Identity_Card <", value, "vipIdentityCard");
			return (Criteria) this;
		}

		public Criteria andVipIdentityCardLessThanOrEqualTo(String value) {
			addCriterion("Vip_Identity_Card <=", value, "vipIdentityCard");
			return (Criteria) this;
		}

		public Criteria andVipIdentityCardLike(String value) {
			addCriterion("Vip_Identity_Card like", value, "vipIdentityCard");
			return (Criteria) this;
		}

		public Criteria andVipIdentityCardNotLike(String value) {
			addCriterion("Vip_Identity_Card not like", value, "vipIdentityCard");
			return (Criteria) this;
		}

		public Criteria andVipIdentityCardIn(List<String> values) {
			addCriterion("Vip_Identity_Card in", values, "vipIdentityCard");
			return (Criteria) this;
		}

		public Criteria andVipIdentityCardNotIn(List<String> values) {
			addCriterion("Vip_Identity_Card not in", values, "vipIdentityCard");
			return (Criteria) this;
		}

		public Criteria andVipIdentityCardBetween(String value1, String value2) {
			addCriterion("Vip_Identity_Card between", value1, value2,
					"vipIdentityCard");
			return (Criteria) this;
		}

		public Criteria andVipIdentityCardNotBetween(String value1,
				String value2) {
			addCriterion("Vip_Identity_Card not between", value1, value2,
					"vipIdentityCard");
			return (Criteria) this;
		}

		public Criteria andVipAddressIsNull() {
			addCriterion("Vip_Address is null");
			return (Criteria) this;
		}

		public Criteria andVipAddressIsNotNull() {
			addCriterion("Vip_Address is not null");
			return (Criteria) this;
		}

		public Criteria andVipAddressEqualTo(String value) {
			addCriterion("Vip_Address =", value, "vipAddress");
			return (Criteria) this;
		}

		public Criteria andVipAddressNotEqualTo(String value) {
			addCriterion("Vip_Address <>", value, "vipAddress");
			return (Criteria) this;
		}

		public Criteria andVipAddressGreaterThan(String value) {
			addCriterion("Vip_Address >", value, "vipAddress");
			return (Criteria) this;
		}

		public Criteria andVipAddressGreaterThanOrEqualTo(String value) {
			addCriterion("Vip_Address >=", value, "vipAddress");
			return (Criteria) this;
		}

		public Criteria andVipAddressLessThan(String value) {
			addCriterion("Vip_Address <", value, "vipAddress");
			return (Criteria) this;
		}

		public Criteria andVipAddressLessThanOrEqualTo(String value) {
			addCriterion("Vip_Address <=", value, "vipAddress");
			return (Criteria) this;
		}

		public Criteria andVipAddressLike(String value) {
			addCriterion("Vip_Address like", value, "vipAddress");
			return (Criteria) this;
		}

		public Criteria andVipAddressNotLike(String value) {
			addCriterion("Vip_Address not like", value, "vipAddress");
			return (Criteria) this;
		}

		public Criteria andVipAddressIn(List<String> values) {
			addCriterion("Vip_Address in", values, "vipAddress");
			return (Criteria) this;
		}

		public Criteria andVipAddressNotIn(List<String> values) {
			addCriterion("Vip_Address not in", values, "vipAddress");
			return (Criteria) this;
		}

		public Criteria andVipAddressBetween(String value1, String value2) {
			addCriterion("Vip_Address between", value1, value2, "vipAddress");
			return (Criteria) this;
		}

		public Criteria andVipAddressNotBetween(String value1, String value2) {
			addCriterion("Vip_Address not between", value1, value2,
					"vipAddress");
			return (Criteria) this;
		}

		public Criteria andVipPhoneNumberIsNull() {
			addCriterion("Vip_Phone_Number is null");
			return (Criteria) this;
		}

		public Criteria andVipPhoneNumberIsNotNull() {
			addCriterion("Vip_Phone_Number is not null");
			return (Criteria) this;
		}

		public Criteria andVipPhoneNumberEqualTo(String value) {
			addCriterion("Vip_Phone_Number =", value, "vipPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andVipPhoneNumberNotEqualTo(String value) {
			addCriterion("Vip_Phone_Number <>", value, "vipPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andVipPhoneNumberGreaterThan(String value) {
			addCriterion("Vip_Phone_Number >", value, "vipPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andVipPhoneNumberGreaterThanOrEqualTo(String value) {
			addCriterion("Vip_Phone_Number >=", value, "vipPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andVipPhoneNumberLessThan(String value) {
			addCriterion("Vip_Phone_Number <", value, "vipPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andVipPhoneNumberLessThanOrEqualTo(String value) {
			addCriterion("Vip_Phone_Number <=", value, "vipPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andVipPhoneNumberLike(String value) {
			addCriterion("Vip_Phone_Number like", value, "vipPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andVipPhoneNumberNotLike(String value) {
			addCriterion("Vip_Phone_Number not like", value, "vipPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andVipPhoneNumberIn(List<String> values) {
			addCriterion("Vip_Phone_Number in", values, "vipPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andVipPhoneNumberNotIn(List<String> values) {
			addCriterion("Vip_Phone_Number not in", values, "vipPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andVipPhoneNumberBetween(String value1, String value2) {
			addCriterion("Vip_Phone_Number between", value1, value2,
					"vipPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andVipPhoneNumberNotBetween(String value1, String value2) {
			addCriterion("Vip_Phone_Number not between", value1, value2,
					"vipPhoneNumber");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_vip
	 * @mbggenerated  Mon Jun 22 20:33:59 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_vip
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 19 09:41:02 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}